# Generated by Django 4.2.1 on 2023-11-21 07:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("book_my_show", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Booking",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("amount", models.FloatField()),
                (
                    "status",
                    models.CharField(
                        choices=[("BOOKED", "Booked"), ("CANCELLED", "Cancelled")],
                        max_length=50,
                    ),
                ),
                ("booked_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="City",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name="Hall",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name="Language",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name="Movie",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("rating", models.IntegerField()),
                ("category", models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name="MovieFeatures",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name="Seat",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("number", models.CharField(max_length=255)),
                ("seat_type", models.CharField(max_length=255)),
                (
                    "hall",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="book_my_show.hall",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Show",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("start_time", models.DateTimeField()),
                ("duration", models.IntegerField()),
                (
                    "features",
                    models.ManyToManyField(
                        limit_choices_to=[
                            ("3D", "Three D"),
                            ("4D", "Four D"),
                            ("IMAX", "Imax"),
                            ("DOLBY_ATMOS", "Dolby"),
                        ],
                        to="book_my_show.moviefeatures",
                    ),
                ),
                (
                    "hall",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="book_my_show.hall",
                    ),
                ),
                (
                    "language",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="book_my_show.language",
                    ),
                ),
                (
                    "movie",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="book_my_show.movie",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Theater",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("address", models.CharField(max_length=255)),
                (
                    "city",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="book_my_show.city",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ShowSeat",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("BOOKED", "Booked"),
                            ("AVAILABLE", "Available"),
                            ("RESERVED", "Reserved"),
                        ],
                        max_length=50,
                    ),
                ),
                (
                    "seat",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="book_my_show.seat",
                    ),
                ),
                (
                    "show",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="book_my_show.show",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Payment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("amount", models.FloatField()),
                (
                    "mode",
                    models.CharField(
                        choices=[
                            ("UPI", "Upi"),
                            ("CREDIT_CARD", "Credit Card"),
                            ("NET_BANKING", "Net Banking"),
                        ],
                        max_length=50,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[("SUCCESS", "Success"), ("FAILED", "Failed")],
                        max_length=50,
                    ),
                ),
                (
                    "booking",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="book_my_show.booking",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="movie",
            name="features",
            field=models.ManyToManyField(
                limit_choices_to=[
                    ("3D", "Three D"),
                    ("4D", "Four D"),
                    ("IMAX", "Imax"),
                    ("DOLBY_ATMOS", "Dolby"),
                ],
                to="book_my_show.moviefeatures",
            ),
        ),
        migrations.AddField(
            model_name="movie",
            name="languages",
            field=models.ManyToManyField(to="book_my_show.language"),
        ),
        migrations.AddField(
            model_name="hall",
            name="theater",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="book_my_show.theater"
            ),
        ),
        migrations.AddField(
            model_name="booking",
            name="seats",
            field=models.ManyToManyField(to="book_my_show.showseat"),
        ),
        migrations.AddField(
            model_name="booking",
            name="show",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="book_my_show.show"
            ),
        ),
        migrations.AddField(
            model_name="booking",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="book_my_show.user"
            ),
        ),
    ]
